"use client";
import Image from "next/image";
import styles from "./ETPSection.module.css";
import { Droplets, FlaskConical, Leaf, Zap, Wind, Waves } from "lucide-react";

const stages = [
  {
    number: "01",
    icon: Waves,
    stage: "Physical Treatment",
    title: "Screening & Sedimentation",
    description:
      "Influent wastewater passes through bar screens and grit chambers to remove large solids, suspended particles, and settleable matter before entering chemical treatment phases.",
    metrics: [{ label: "Solids Removal", value: ">95%" }, { label: "Stage", value: "Primary" }],
  },
  {
    number: "02",
    icon: FlaskConical,
    stage: "Chemical Treatment",
    title: "COD/BOD Neutralization",
    description:
      "Coagulation and flocculation agents are precisely dosed to neutralize Chemical Oxygen Demand (COD) and Biological Oxygen Demand (BOD). pH is balanced to safe discharge levels.",
    metrics: [{ label: "COD Reduction", value: ">85%" }, { label: "pH Control", value: "6.5–8.5" }],
  },
  {
    number: "03",
    icon: Droplets,
    stage: "Biological Treatment",
    title: "Aerobic Digestion",
    description:
      "Activated sludge processes and aeration tanks house microbial cultures that biologically degrade remaining organic compounds, completing the purification cycle.",
    metrics: [{ label: "BOD Reduction", value: ">90%" }, { label: "Sludge", value: "Managed" }],
  },
  {
    number: "04",
    icon: Leaf,
    stage: "Tertiary & ZLD",
    title: "Zero-Liquid Discharge",
    description:
      "Advanced filtration, RO membranes, and evaporation systems achieve Zero-Liquid Discharge — 100% of treated water is recovered and recycled back into the dyeing process.",
    metrics: [{ label: "Water Recovery", value: "100%" }, { label: "Discharge", value: "Zero" }],
  },
];

const greenTech = [
  { icon: Leaf, label: "Zero-Liquid Discharge (ZLD)", desc: "Complete water recycling — zero external discharge" },
  { icon: Zap, label: "Energy-Efficient Pumps", desc: "Variable frequency drives reduce energy consumption by 30%" },
  { icon: Wind, label: "Traceable Waste Streams", desc: "Full chain documentation for all waste materials" },
  { icon: Droplets, label: "Chemical Recovery", desc: "Dye chemicals recovered and reused in formulation" },
];

export default function ETPSection() {
  return (
    <section id="etp" className={`${styles.section} bg-etp`}>
      <div className="container">
        {/* Header */}
        <div className={styles.header}>
          <span className="label-text" style={{ color: "#14A085" }}>Eco-Stewardship</span>
          <div className={styles.tealDivider} />
          <h2 className={`section-title ${styles.headline}`}>
            In-House <span className="teal-text">ETP Facility</span> &amp;<br />
            Environmental Commitment
          </h2>
          <p className={styles.headerSub}>
            Operated under Shiva Shakthi Marketing, our multi-stage Effluent Treatment Plant
            neutralizes all dyeing effluents before achieving zero liquid discharge.
          </p>
        </div>

        {/* ETP Image + Intro */}
        <div className={styles.introGrid}>
          <div className={styles.etpImageWrap}>
            <Image
              src="/etp_facility.png"
              alt="Shiva Shakthi Marketing ETP Facility"
              fill
              className="img-cover"
            />
            <div className={styles.etpImageOverlay} />
            <div className={styles.etpImageLabel}>
              <Droplets size={16} />
              ETP Operations · Doddaballapura Plant
            </div>
          </div>
          <div className={styles.introText}>
            <p className={styles.introPara}>
              The textile dyeing process generates chemically complex effluent streams containing
              synthetic dyes, surfactants, and auxiliary chemicals. Left untreated, these cause
              severe ecological damage to local water bodies.
            </p>
            <p className={styles.introPara}>
              Our state-of-the-art in-house ETP — a rare capability in the industry — ensures
              that every liter of wastewater generated by our 35-ton monthly dyeing operations
              undergoes rigorous multi-stage treatment before being reclaimed.
            </p>
            <div className={styles.certTags}>
              <span className="badge badge-teal">ETP Certified</span>
              <span className="badge badge-teal">ZLD Compliant</span>
              <span className="badge badge-green">Eco-Audited</span>
            </div>
          </div>
        </div>

        {/* Process Flow */}
        <div className={styles.processTitle}>
          <div className={styles.tealLine} />
          <span className="label-text" style={{ color: "#14A085" }}>Multi-Stage Purification Process</span>
          <div className={styles.tealLine} />
        </div>

        <div className={styles.stageGrid}>
          {stages.map((stage, i) => {
            const Icon = stage.icon;
            return (
              <div key={stage.number} className={styles.stageCard}>
                {/* Connector */}
                {i < stages.length - 1 && <div className={styles.connector} />}

                <div className={styles.stageNumber}>{stage.number}</div>
                <div className={styles.stageIconWrap}>
                  <Icon size={24} strokeWidth={1.5} />
                </div>
                <div className={styles.stageBadge}>{stage.stage}</div>
                <h3 className={styles.stageTitle}>{stage.title}</h3>
                <p className={styles.stageDesc}>{stage.description}</p>
                <div className={styles.stageMetrics}>
                  {stage.metrics.map((m) => (
                    <div key={m.label} className={styles.metric}>
                      <span className={styles.metricVal}>{m.value}</span>
                      <span className={styles.metricLabel}>{m.label}</span>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>

        {/* Green Tech Grid */}
        <div className={styles.greenGrid}>
          {greenTech.map((tech) => {
            const Icon = tech.icon;
            return (
              <div key={tech.label} className={styles.greenCard}>
                <div className={styles.greenIconWrap}>
                  <Icon size={20} strokeWidth={1.5} />
                </div>
                <div>
                  <p className={styles.greenLabel}>{tech.label}</p>
                  <p className={styles.greenDesc}>{tech.desc}</p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
